### ISSUE TITLE
Reconnect context menu

### ISSUE THREAD

**Issue by hafedh-trimeche** [maxsnts/XwRemote#18]
Hello,

Would Reconnect action be added to a Tab context menu to avoid closing an reopening Connection?

Best regards.

**Comment by maxsnts** [comment]
Hi
RDP already as a button "Connect" in the middle of the screen when the connection drops.
Other protocols have their own peculiarities.
I'm partial to the big "connect" button over the contact menu, but i can will see what i can do.
Can you tell me on what protocol do you miss this feature?
Thank you

**Comment by hafedh-trimeche** [comment]
Hi,

Actually I am testing SSH connections.

Thanks.

**Comment by maxsnts** [comment]
When the connection drops/breaks the tab do not close?
I have no way to distinguish from a broken connection or a CTRL-D (logout) on the remote ssh server.
Since "Logout" from the remote is more common than a broken connection, i opted to close the tab.
The only time o think a "Connect" or option would help is when the connection fails from the start.
Can you say when (in what situation) is the reconnect option useful? How can a simulate it.
Thank you

**Comment by hafedh-trimeche** [comment]
Please note that when remote Host is rebooted/powered off from command line or Hypervisor Management Console, it would be better to reopen connection to the same host instead of closing & reopening Tab because the Tab still visible without indicating that the connection is lost.

Thanks.

**Comment by maxsnts** [comment]
Next version will have a "Connect" button on the SSH tabs that lost connection.
![image](https://user-images.githubusercontent.com/3869164/198902216-667b6c77-205d-41eb-8dca-b123e7a6df20.png)
