### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by kiuX89** [maxsnts/XwRemote#28]
Hello, I'm currently using your software and I think it's better than the current competitors and I'd like to thank you for your work. 
However, I wonder if you've considered portability to Mac or Linux? 

Sincerely

**Comment by maxsnts** [comment]
Hello, Thank you.

Yes, i have wondered about portability, and i would love to do it since i'm a Mac and Linux user. 
(I use all 3 OSs at the same time with VMs)

However this is a very Windows centric software.
First is done with .Net, and .net GUI application in MAC and Linux are very week.

However the biggest problem is that there is no good RDP control that i can embed on Mac and Linux.
I'm not smart enough to implement the complete protocol myself.  

I would love this, and from time to time i "shop around" looking for a solution, but i have not found any.
